In [280]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [281]:
engagements=pd.read_csv('clean_preprocessed_email_engagements.csv')

In [282]:
features=pd.read_excel('features_list.xlsx')

In [284]:
features

,Sr. No.,Feature,Description
0,1,First Name,Prospect First Name
1,2,Last Name,Prospect Last Name
2,3,Level,Prospect Job Level
3,4,Title,Prospect Job Title
4,5,Department,Prospect Department
5,6,Seniority,Prospect Seniority
6,7,Company Name,Prospect Company Name
7,8,Website,Prospect Comapny Domain
8,9,Email,Prospect Email
9,10,Contact Country,Prospect Country
10,11,Company Revenue Range,Companies Annual Revenue Range
11,12,Company Industry,Prospect Company Industry
12,13,Company Employee Range,Companies Employee Count Rane
13,14,Total Emails Sent,Total Emails Sent To Prospect
14,16,Total Email Opened,Total Emails Open By Prospect
15,17,Total Email Unsubscribed,Total Emails Unsubscribed By Prospect
16,18,Total Bounced,Total Emails Bounced By Prospect
17,19,Total Responded Emails,Total Emails Responded By Prospect
18,20,Total Emails Sent Last 4 Weeks,Total Emails Sent To Prospect In Last 4 Weeks
19,21,Total Emails Sent Last 8 Weeks,Total Emails Sent To Prospect In Last 8 Weeks
20,22,Total Emails Sent Last 12 Weeks,Total Emails Sent To Prospect In Last 12 Weeks
21,23,Total Emails Opened Last 4 Weeks,Total Emails Opened By Prospect In Last 4 Weeks
22,24,Total Emails Opened Last 8 Weeks,Total Emails Opened By Prospect In Last 8 Weeks
23,25,Total Emails Opened Last 12 Weeks,Total Emails Opened By Prospect In Last 12 Weeks
24,26,Total Emails Send On Week-Ends (Saturday-Sunday),Count Of Total Emails Sent To Prospect On Satu...
25,27,Email Bounce Rate,Total Bounced Emails/Total Emails Sent
26,28,Email Open Rate,Total Open Emails/Total Emails Sent
27,29,Last Email Status,Status Of Recently Sent Email To Prospect (EMA...
28,30,Days Since Last Email Opened,Number Of Days Elapsed Since The Last Email Wa...
29,31,Days Since Last Email Sent,Number Of Days Elapsed Since The Last Email Se...
30,33,Has Ever Opened Email,Binary Indicator To Check Is Prospect Ever Ope...
31,34,Has Ever Unsubscribed Email,Binary Indicator To Check Is Prospect Ever Uns...
32,35,Total Email Sent In Morning,Total Emails Sent To Prospect In Morning
33,36,Total Email Sent In Afternoon,Total Emails Sent To Prospect In Afternoon
34,37,Total Email Sent In Evening,Total Emails Sent To Prospect In Evening
35,38,Total Email Sent In Night,Total Emails Sent To Prospect In Night
36,39,Total Email Sent On Monday,Total Emails Sent To Prospect On Monday
37,40,Total Email Sent On Tuesday,Total Emails Sent To Prospect On Tuesday
38,41,Total Email Sent On Wednesday,Total Emails Sent To Prospect On Wednesday
39,42,Total Email Sent On Thursday,Total Emails Sent To Prospect On Thursday
40,43,Total Email Sent On Friday,Total Emails Sent To Prospect On Friday
41,44,Total Email Sent On Saturday,Total Emails Sent To Prospect On Saturday
42,45,Total Email Sent On Sunday,Total Emails Sent To Prospect On Sunday
43,46,Number Of Days Taken To Open First Email,Number Of Days Taken By Prospects To Open The ...
44,47,Number Of Days Elapsed Sinse First Email Open,Number Of Days Elapsed Sinse First The Email ...
45,48,engagement_density,Total Emails Sent/Total Days Targeted Prospect
46,49,Has Unsubscribed First Email,1 if prospect unsubscribed first email else 0

In [286]:
engagements

,FirstName,CompanyName,source,header_date,raw_status,status,status_time,reason,status_time_utc,Email,...,Reward,timezone,status_time_clean,email_sent_et,new_header_date,final_status_time,first_email_sent_date,one_week_later,campaign_start_date,campaign_end_date
0,Larry,Intel,June 2024/Schneider_SemiConductorDel2&3_Father...,2024-06-13,EMAIL_NOT_SENT,EMAIL_NOT_SENT,NaN,NaN,NaN,9fake@thomasfellows.com,...,$100,ET,NaN,NaN,2024-06-13 12:00:00,2024-06-13 12:00:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
1,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-18,EMAIL_SENT # 06/18/2024 - 06:01 PM UTC,EMAIL_SENT,06/18/2024 - 06:01 PM UTC,NaN,2024-06-18 18:01:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/18/2024 - 06:01 PM,2024-06-18 14:01:00-04:00,2024-06-18 12:00:00,2024-06-18 18:01:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
2,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-19,EMAIL_SENT # 06/19/2024 - 03:28 PM UTC,EMAIL_SENT,06/19/2024 - 03:28 PM UTC,NaN,2024-06-19 15:28:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/19/2024 - 03:28 PM,2024-06-19 11:28:00-04:00,2024-06-19 12:00:00,2024-06-19 15:28:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
3,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-20,EMAIL_SENT # 06/20/2024 - 02:03 PM UTC,EMAIL_SENT,06/20/2024 - 02:03 PM UTC,NaN,2024-06-20 14:03:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/20/2024 - 02:03 PM,2024-06-20 10:03:00-04:00,2024-06-20 12:00:00,2024-06-20 14:03:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
4,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-21,EMAIL_SENT # 06/21/2024 - 04:42 PM UTC,EMAIL_SENT,06/21/2024 - 04:42 PM UTC,NaN,2024-06-21 16:42:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/21/2024 - 04:42 PM,2024-06-21 12:42:00-04:00,2024-06-21 12:00:00,2024-06-21 16:42:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009905,È”Šæ±Ÿ,General Motors-Opel,July 2024/Schneider_EV_Del _1to4_30thJuly_2024...,2024-07-30,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,EMAIL_NOT_SENT,07/30/2024 - 04:58 PM UTC,NaN,2024-07-30 16:58:00+00:00,è”šæ±ÿ.æ–‡@gm.com,...,$100,ET,07/30/2024 - 04:58 PM,2024-07-30 12:58:00-04:00,2024-07-30 12:00:00,2024-07-30 16:58:00,2024-05-16 08:00:00-04:00,2024-05-23 08:00:00-04:00,2024-05-16 08:00:00-04:00,2024-08-23 11:53:00-04:00
4009906,é˜³é˜³,AECOM/URS,September 2024/SE_Roboticsdel3_19Sep_2024-19_S...,2024-09-19,ERROR # Invalid email,ERROR,NaN,Invalid email,NaN,é˜³é˜³.é­@aecom.com,...,$100,ET,NaN,NaN,2024-09-19 12:00:00,2024-09-19 12:00:00,2024-09-19 08:00:00-04:00,2024-09-26 08:00:00-04:00,2024-09-06 08:00:00-04:00,2024-12-09 11:02:00-05:00
4009907,é˜³é˜³,AECOM/URS,September 2024/SE_Roboticsdel3_19Sep_2024-19_S...,2024-09-20,ERROR,ERROR,NaN,NaN,NaN,é˜³é˜³.é­@aecom.com,...,$100,ET,NaN,NaN,2024-09-20 12:00:00,2024-09-20 12:00:00,2024-09-19 08:00:00-04:00,2024-09-26 08:00:00-04:00,2024-09-06 08:00:00-04:00,2024-12-09 11:02:00-05:00
4009908,é˜³é˜³,AECOM/URS,September 2024/SE_Roboticsdel3_19Sep_2024-19_S...,2024-09-21,EMAIL_NOT_SENT,EMAIL_NOT_SENT,NaN,NaN,NaN,é˜³é˜³.é­@aecom.com,...,$100,ET,NaN,NaN,2024-09-21 12:00:00,2024-09-21 12:00:00,2024-09-19 08:00:00-04:00,2024-09-26 08:00:00-04:00,2024-09-06 08:00:00-04:00,2024-12-09 11:02:00-05:00
4009909,é˜³é˜³,AECOM/URS,October 2024/Schneider_Robotics_Del2to4_29thOc...,2024-10-29,"ERROR # Invalid email: ""É˜³é˜³ É­"" <é˜³é˜³.é­...",ERROR,NaN,"""É˜³é˜³ É­"" <é˜³é˜³.é­@aecom.com>",NaN,é˜³é˜³.é­@aecom.com,...,$100,ET,NaN,NaN,2024-10-29 12:00:00,2024-10-29 12:00:00,2024-09-19 08:00:00-04:00,2024-09-26 08:00:00-04:00,2024-09-06 08:00:00-04:00,2024-12-09 11:02:00-05:00

In [303]:
engagements.groupby('Email').size()

Email
9fake@thomasfellows.com                     7
Adaku.Ude@sfdph.org                        13
Ahess@amgen.com                             3
Carlos.Perez@thermofisher.com               4
CarlosOliverMontejano.Ramirez@magna.com    22
                                           ..
å©§å¼ @ashleyfurniture.com                  2
å¸†æ¨@its.jnj.com                          2
æ´å¼ @its.jnj.com                          2
è”šæ±ÿ.æ–‡@gm.com                          40
é˜³é˜³.é­@aecom.com                        4
Length: 157169, dtype: int64

In [293]:
engagements[engagements['Email']=='Adaku.Ude@sfdph.org'].shape

(13, 30)

In [295]:

import pytz


df = pd.read_csv('clean_preprocessed_email_engagements.csv')


df['new_header_date'] = pd.to_datetime(df['new_header_date'], errors='coerce', utc=True)
df['final_status_time'] = pd.to_datetime(df['final_status_time'], errors='coerce', utc=True)


mask = df['timezone'].str.upper() != 'ET'


et = pytz.timezone('US/Eastern')

df.loc[mask, 'new_header_date'] = df.loc[mask, 'new_header_date'].apply(lambda x: x.astimezone(et) if pd.notnull(x) else x)
df.loc[mask, 'final_status_time'] = df.loc[mask, 'final_status_time'].apply(lambda x: x.astimezone(et) if pd.notnull(x) else x)


df.loc[mask, 'timezone'] = 'ET'

df.head()

,FirstName,CompanyName,source,header_date,raw_status,status,status_time,reason,status_time_utc,Email,...,Reward,timezone,status_time_clean,email_sent_et,new_header_date,final_status_time,first_email_sent_date,one_week_later,campaign_start_date,campaign_end_date
0,Larry,Intel,June 2024/Schneider_SemiConductorDel2&3_Father...,2024-06-13,EMAIL_NOT_SENT,EMAIL_NOT_SENT,NaN,NaN,NaN,9fake@thomasfellows.com,...,$100,ET,NaN,NaN,2024-06-13 12:00:00+00:00,2024-06-13 12:00:00+00:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
1,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-18,EMAIL_SENT # 06/18/2024 - 06:01 PM UTC,EMAIL_SENT,06/18/2024 - 06:01 PM UTC,NaN,2024-06-18 18:01:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/18/2024 - 06:01 PM,2024-06-18 14:01:00-04:00,2024-06-18 12:00:00+00:00,2024-06-18 18:01:00+00:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
2,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-19,EMAIL_SENT # 06/19/2024 - 03:28 PM UTC,EMAIL_SENT,06/19/2024 - 03:28 PM UTC,NaN,2024-06-19 15:28:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/19/2024 - 03:28 PM,2024-06-19 11:28:00-04:00,2024-06-19 12:00:00+00:00,2024-06-19 15:28:00+00:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
3,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-20,EMAIL_SENT # 06/20/2024 - 02:03 PM UTC,EMAIL_SENT,06/20/2024 - 02:03 PM UTC,NaN,2024-06-20 14:03:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/20/2024 - 02:03 PM,2024-06-20 10:03:00-04:00,2024-06-20 12:00:00+00:00,2024-06-20 14:03:00+00:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
4,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-21,EMAIL_SENT # 06/21/2024 - 04:42 PM UTC,EMAIL_SENT,06/21/2024 - 04:42 PM UTC,NaN,2024-06-21 16:42:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/21/2024 - 04:42 PM,2024-06-21 12:42:00-04:00,2024-06-21 12:00:00+00:00,2024-06-21 16:42:00+00:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00

In [296]:
import pandas as pd
import pytz

df = pd.read_csv('clean_preprocessed_email_engagements.csv')

df['new_header_date'] = pd.to_datetime(df['new_header_date'], errors='coerce', utc=True)
df['final_status_time'] = pd.to_datetime(df['final_status_time'], errors='coerce', utc=True)


mask = df['timezone'].str.upper() != 'ET'
et = pytz.timezone('US/Eastern')

df.loc[mask, 'new_header_date'] = df.loc[mask, 'new_header_date'].apply(
    lambda x: x.astimezone(et) if pd.notnull(x) else x
)
df.loc[mask, 'final_status_time'] = df.loc[mask, 'final_status_time'].apply(
    lambda x: x.astimezone(et) if pd.notnull(x) else x
)


df.loc[mask, 'timezone'] = 'ET'


df['new_header_date'] = df['new_header_date'].dt.strftime('%Y-%m-%d %H:%M:%S')
df['final_status_time'] = df['final_status_time'].dt.strftime('%Y-%m-%d %H:%M:%S')


df.to_csv('clean_preprocessed_email_engagements.csv', index=False)

In [297]:
eng = pd.read_csv('clean_preprocessed_email_engagements.csv')

In [299]:
eng

,FirstName,CompanyName,source,header_date,raw_status,status,status_time,reason,status_time_utc,Email,...,Reward,timezone,status_time_clean,email_sent_et,new_header_date,final_status_time,first_email_sent_date,one_week_later,campaign_start_date,campaign_end_date
0,Larry,Intel,June 2024/Schneider_SemiConductorDel2&3_Father...,2024-06-13,EMAIL_NOT_SENT,EMAIL_NOT_SENT,NaN,NaN,NaN,9fake@thomasfellows.com,...,$100,ET,NaN,NaN,2024-06-13 12:00:00,2024-06-13 12:00:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
1,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-18,EMAIL_SENT # 06/18/2024 - 06:01 PM UTC,EMAIL_SENT,06/18/2024 - 06:01 PM UTC,NaN,2024-06-18 18:01:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/18/2024 - 06:01 PM,2024-06-18 14:01:00-04:00,2024-06-18 12:00:00,2024-06-18 18:01:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
2,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-19,EMAIL_SENT # 06/19/2024 - 03:28 PM UTC,EMAIL_SENT,06/19/2024 - 03:28 PM UTC,NaN,2024-06-19 15:28:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/19/2024 - 03:28 PM,2024-06-19 11:28:00-04:00,2024-06-19 12:00:00,2024-06-19 15:28:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
3,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-20,EMAIL_SENT # 06/20/2024 - 02:03 PM UTC,EMAIL_SENT,06/20/2024 - 02:03 PM UTC,NaN,2024-06-20 14:03:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/20/2024 - 02:03 PM,2024-06-20 10:03:00-04:00,2024-06-20 12:00:00,2024-06-20 14:03:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
4,Larry,Intel,June 2024/Schneider_SemiConductorDel1&3_Summer...,2024-06-21,EMAIL_SENT # 06/21/2024 - 04:42 PM UTC,EMAIL_SENT,06/21/2024 - 04:42 PM UTC,NaN,2024-06-21 16:42:00+00:00,9fake@thomasfellows.com,...,$100,ET,06/21/2024 - 04:42 PM,2024-06-21 12:42:00-04:00,2024-06-21 12:00:00,2024-06-21 16:42:00,2024-06-13 08:00:00-04:00,2024-06-20 08:00:00-04:00,2024-05-29 08:00:00-04:00,2024-09-08 22:24:00-04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4009905,È”Šæ±Ÿ,General Motors-Opel,July 2024/Schneider_EV_Del _1to4_30thJuly_2024...,2024-07-30,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,EMAIL_NOT_SENT,07/30/2024 - 04:58 PM UTC,NaN,2024-07-30 16:58:00+00:00,è”šæ±ÿ.æ–‡@gm.com,...,$100,ET,07/30/2024 - 04:58 PM,2024-07-30 12:58:00-04:00,2024-07-30 12:00:00,2024-07-30 16:58:00,2024-05-16 08:00:00-04:00,2024-05-23 08:00:00-04:00,2024-05-16 08:00:00-04:00,2024-08-23 11:53:00-04:00
4009906,é˜³é˜³,AECOM/URS,September 2024/SE_Roboticsdel3_19Sep_2024-19_S...,2024-09-19,ERROR # Invalid email,ERROR,NaN,Invalid email,NaN,é˜³é˜³.é­@aecom.com,...,$100,ET,NaN,NaN,2024-09-19 12:00:00,2024-09-19 12:00:00,2024-09-19 08:00:00-04:00,2024-09-26 08:00:00-04:00,2024-09-06 08:00:00-04:00,2024-12-09 11:02:00-05:00
4009907,é˜³é˜³,AECOM/URS,September 2024/SE_Roboticsdel3_19Sep_2024-19_S...,2024-09-20,ERROR,ERROR,NaN,NaN,NaN,é˜³é˜³.é­@aecom.com,...,$100,ET,NaN,NaN,2024-09-20 12:00:00,2024-09-20 12:00:00,2024-09-19 08:00:00-04:00,2024-09-26 08:00:00-04:00,2024-09-06 08:00:00-04:00,2024-12-09 11:02:00-05:00
4009908,é˜³é˜³,AECOM/URS,September 2024/SE_Roboticsdel3_19Sep_2024-19_S...,2024-09-21,EMAIL_NOT_SENT,EMAIL_NOT_SENT,NaN,NaN,NaN,é˜³é˜³.é­@aecom.com,...,$100,ET,NaN,NaN,2024-09-21 12:00:00,2024-09-21 12:00:00,2024-09-19 08:00:00-04:00,2024-09-26 08:00:00-04:00,2024-09-06 08:00:00-04:00,2024-12-09 11:02:00-05:00
4009909,é˜³é˜³,AECOM/URS,October 2024/Schneider_Robotics_Del2to4_29thOc...,2024-10-29,"ERROR # Invalid email: ""É˜³é˜³ É­"" <é˜³é˜³.é­...",ERROR,NaN,"""É˜³é˜³ É­"" <é˜³é˜³.é­@aecom.com>",NaN,é˜³é˜³.é­@aecom.com,...,$100,ET,NaN,NaN,2024-10-29 12:00:00,2024-10-29 12:00:00,2024-09-19 08:00:00-04:00,2024-09-26 08:00:00-04:00,2024-09-06 08:00:00-04:00,2024-12-09 11:02:00-05:00

In [305]:
opened_emails = eng[eng['raw_status'].str.contains('EMAIL_OPENED')].groupby('Email').size().reset_index(name='total_emails_clicked')
opened_emails

                         Email  total_emails_clicked
0        a.akingboju@apple.com                    15
1      a.alexander@samsung.com                     1
2        a.calzola@samsung.com                     2
3        a.freitas@samsung.com                     1
4     a.harrington@samsung.com                     3
...                        ...                   ...
9231     zrogers@coca-cola.com                     2
9232        zsiddiq@rivian.com                     2
9233    zstoller@coca-cola.com                     2
9234   zurielsuarez@dswinc.com                     2
9235         è”šæ±ÿ.æ–‡@gm.com                     1

[9236 rows x 2 columns]

In [308]:
df = eng.groupby('Email').size().reset_index(name='total_emails')

In [309]:
df

                                          Email  total_emails
0                       9fake@thomasfellows.com             7
1                           Adaku.Ude@sfdph.org            13
2                               Ahess@amgen.com             3
3                 Carlos.Perez@thermofisher.com             4
4       CarlosOliverMontejano.Ramirez@magna.com            22
...                                         ...           ...
157164               å©§å¼ @ashleyfurniture.com             2
157165                       å¸†æ¨@its.jnj.com             2
157166                       æ´å¼ @its.jnj.com             2
157167                        è”šæ±ÿ.æ–‡@gm.com            40
157168                     é˜³é˜³.é­@aecom.com             4

[157169 rows x 2 columns]

In [312]:
df=df.merge(opened_emails,on='Email',how='left')

In [314]:
df

,Email,total_emails,total_emails_clicked
0,9fake@thomasfellows.com,7,NaN
1,Adaku.Ude@sfdph.org,13,NaN
2,Ahess@amgen.com,3,NaN
3,Carlos.Perez@thermofisher.com,4,NaN
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN
...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN
157165,å¸†æ¨@its.jnj.com,2,NaN
157166,æ´å¼ @its.jnj.com,2,NaN
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0
157168,é˜³é˜³.é­@aecom.com,4,NaN

In [316]:
df.to_csv('test.csv',index=False)

In [319]:
unsubscribed_emails = eng[eng['raw_status'].str.contains('UNSUBSCRIBED', na=False)].groupby('Email').size().reset_index(name='total_emails_unsubscribed')
unsubscribed_emails

                         Email  total_emails_unsubscribed
0        aaron.bailey@lmco.com                          2
1         abyun@dfwairport.com                          3
2             achacon@ford.com                          1
3       acraig@waste2water.com                          1
4        adam.dobbs@mspmac.org                          1
..                         ...                        ...
963           yuchen.du@gf.com                          1
964     yvan.chouinard@kcc.com                          1
965  zachary.r.rasmor@lmco.com                          2
966     zailong.bian@intel.com                          1
967             zolson@san.org                          1

[968 rows x 2 columns]

In [320]:
df=df.merge(unsubscribed_emails,on='Email',how='left')

In [323]:
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed
0,9fake@thomasfellows.com,7,NaN,NaN
1,Adaku.Ude@sfdph.org,13,NaN,NaN
2,Ahess@amgen.com,3,NaN,NaN
3,Carlos.Perez@thermofisher.com,4,NaN,NaN
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN
...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN
157166,æ´å¼ @its.jnj.com,2,NaN,NaN
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN

In [325]:
bounced_emails = eng[eng['raw_status'].str.contains('BOUNCE', na=False)].groupby('Email').size().reset_index(name='total_emails_bounced')
bounced_emails

                                         Email  total_emails_bounced
0                      9fake@thomasfellows.com                     1
1                              Ahess@amgen.com                     1
2      CarlosOliverMontejano.Ramirez@magna.com                     2
3                            GRogers@lilly.com                     1
4                           Ian.Corn@lilly.com                     1
...                                        ...                   ...
40210                         zwright@ford.com                     1
40211                           zxu@micron.com                     1
40212                  zyongping@plugpower.com                     1
40213                         zzhao@micron.com                     1
40214              Ï­Ïƒ.bush@hrsolutionsoc.com                     1

[40215 rows x 2 columns]

In [327]:
df=df.merge(bounced_emails,on='Email',how='left')

In [329]:
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced
0,9fake@thomasfellows.com,7,NaN,NaN,1.0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN
2,Ahess@amgen.com,3,NaN,NaN,1.0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0
...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN

In [331]:
responded_emails = eng[eng['raw_status'].str.contains('RESPONDED', na=False)].groupby('Email').size().reset_index(name='total_emails_responded')
responded_emails

                              Email  total_emails_responded
0               aaron.b@pentair.com                       1
1                   abhinavg@vt.edu                       1
2         ahuey@calvaryrobotics.com                       1
3        barbara.bussen@pentair.com                       1
4        betty.schiller@pentair.com                       1
5           bill.hurguy@pentair.com                       1
6               brugman@pentair.com                       1
7   ccasciole@ferrerocontainers.com                       2
8           chiyul.yoon@samsung.com                       1
9            coxeverett@pentair.com                       1
10               d.jung@samsung.com                      14
11                 ecabrera@san.org                       1
12             eric.lee@pentair.com                       1
13                 eshull@dpump.com                      13
14             g.cabral@samsung.com                       8
15           gunill.lee@samsung.com                       1
16           hugo.ramos@pentair.com                       1
17       ipierpont@tampaairport.com                       2
18          jaewook.lee@samsung.com                       1
19          jimin.chung@samsung.com                       1
20            julie.lee@samsung.com                       1
21    julie.leung@northhighland.com                       1
22         kelly.adkins@pentair.com                       1
23      kenneth.hoskins@pentair.com                       1
24        kent.oxley@exeloncorp.com                       1
25                ktaylor@dpump.com                      13
26           ktruell@mindspring.com                       4
27              l.goral@samsung.com                       2
28         lucy.bergman@pentair.com                       1
29           meymand@mindspring.com                      16
30      michael.craven@avangrid.com                       3
31       milan.petricko@pentair.com                       1
32         nathan.drees@pentair.com                       1
33            orlando.d@pentair.com                       1
34       ray.engelhardt@pentair.com                       1
35      roberta.bailey@avangrid.com                      20
36               ryan.c@samsung.com                       7
37                sam.p@pentair.com                       1
38          scott.baker@pentair.com                       1
39               shaun@flexicon.com                      12
40               stortiw@wseinc.com                       1
41                ttran@samsung.com                      14

In [332]:
df=df.merge(responded_emails,on='Email',how='left')

In [335]:
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN
...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN

In [337]:
has_unsubscribed = eng[(eng['raw_status'].str.contains('UNSUBSCRIBE', na=False)) & 
                       (eng['status_time'] == eng['first_email_sent_date'])] \
                   .drop_duplicates('Email')[['Email']]
has_unsubscribed['has_unsubscribed_first_email'] = 1

result = eng[['Email']].drop_duplicates().merge(has_unsubscribed, on='Email', how='left')
result['has_unsubscribed_first_email'] = result['has_unsubscribed_first_email'].fillna(0).astype(int)
result

                                          Email  has_unsubscribed_first_email
0                       9fake@thomasfellows.com                             0
1                           Adaku.Ude@sfdph.org                             0
2                               Ahess@amgen.com                             0
3                 Carlos.Perez@thermofisher.com                             0
4       CarlosOliverMontejano.Ramirez@magna.com                             0
...                                         ...                           ...
157164               å©§å¼ @ashleyfurniture.com                             0
157165                       å¸†æ¨@its.jnj.com                             0
157166                       æ´å¼ @its.jnj.com                             0
157167                        è”šæ±ÿ.æ–‡@gm.com                             0
157168                     é˜³é˜³.é­@aecom.com                             0

[157169 rows x 2 columns]

In [339]:
df=df.merge(result,on='Email',how='left')

In [341]:
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0
...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0

In [343]:
import pandas as pd

# Load your data
eng = pd.read_csv('clean_preprocessed_email_engagements.csv')

# Ensure column names are clean and lowercase for safety
eng.columns = eng.columns.str.strip()

# Mark bounced emails
eng['is_bounced'] = eng['raw_status'].str.lower() == 'bounced'

# Total emails sent per prospect
total_sent = eng.groupby('Email').size().reset_index(name='total_sent')

# Total bounced emails per prospect
total_bounced = eng[eng['is_bounced']].groupby('Email').size().reset_index(name='total_bounced')

# Merge and compute bounce rate per email
bounce_rate_df = total_sent.merge(total_bounced, on='Email', how='left')
bounce_rate_df['total_bounced'] = bounce_rate_df['total_bounced'].fillna(0)
bounce_rate_df['email_bounce_rate'] = bounce_rate_df['total_bounced'] / bounce_rate_df['total_sent']

# Final result
bounce_rate_df = bounce_rate_df[['Email', 'email_bounce_rate']]
print(bounce_rate_df)

                                          Email  email_bounce_rate
0                       9fake@thomasfellows.com           0.000000
1                           Adaku.Ude@sfdph.org           0.000000
2                               Ahess@amgen.com           0.000000
3                 Carlos.Perez@thermofisher.com           0.000000
4       CarlosOliverMontejano.Ramirez@magna.com           0.045455
...                                         ...                ...
157164               å©§å¼ @ashleyfurniture.com           0.000000
157165                       å¸†æ¨@its.jnj.com           0.000000
157166                       æ´å¼ @its.jnj.com           0.000000
157167                        è”šæ±ÿ.æ–‡@gm.com           0.000000
157168                     é˜³é˜³.é­@aecom.com           0.000000

[157169 rows x 2 columns]

In [344]:
df = df.merge(bounce_rate_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455
...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000

In [347]:
# Mark opened emails
eng['is_opened'] = eng['raw_status'].str.lower().str.contains('open', na=False)

# Total emails sent per prospect
total_sent = eng.groupby('Email').size().reset_index(name='total_sent')

# Total opened emails per prospect
total_opened = eng[eng['is_opened']].groupby('Email').size().reset_index(name='total_opened')

# Merge and compute open rate per email
open_rate_df = total_sent.merge(total_opened, on='Email', how='left')
open_rate_df['total_opened'] = open_rate_df['total_opened'].fillna(0)
open_rate_df['email_open_rate'] = open_rate_df['total_opened'] / open_rate_df['total_sent']

# Final result
open_rate_df = open_rate_df[['Email', 'email_open_rate']]
print(open_rate_df)

                                          Email  email_open_rate
0                       9fake@thomasfellows.com            0.000
1                           Adaku.Ude@sfdph.org            0.000
2                               Ahess@amgen.com            0.000
3                 Carlos.Perez@thermofisher.com            0.000
4       CarlosOliverMontejano.Ramirez@magna.com            0.000
...                                         ...              ...
157164               å©§å¼ @ashleyfurniture.com            0.000
157165                       å¸†æ¨@its.jnj.com            0.000
157166                       æ´å¼ @its.jnj.com            0.000
157167                        è”šæ±ÿ.æ–‡@gm.com            0.025
157168                     é˜³é˜³.é­@aecom.com            0.000

[157169 rows x 2 columns]

In [348]:
df = df.merge(open_rate_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000
...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000

In [350]:
eng_sorted = eng.sort_values(['Email', 'status_time'], ascending=[True, False])

# Get the last status per Email
last_status_df = eng_sorted.groupby('Email').first().reset_index()

# Extract the last email status
last_status_df = last_status_df[['Email', 'raw_status']].rename(columns={'raw_status': 'last_email_status'})
print(last_status_df)

                                          Email  \
0                       9fake@thomasfellows.com
1                           Adaku.Ude@sfdph.org
2                               Ahess@amgen.com
3                 Carlos.Perez@thermofisher.com
4       CarlosOliverMontejano.Ramirez@magna.com
...                                         ...
157164               å©§å¼ @ashleyfurniture.com
157165                       å¸†æ¨@its.jnj.com
157166                       æ´å¼ @its.jnj.com
157167                        è”šæ±ÿ.æ–‡@gm.com
157168                     é˜³é˜³.é­@aecom.com

                                 last_email_status
0           EMAIL_SENT # 06/22/2024 - 03:26 PM UTC
1           EMAIL_SENT # 11/02/2024 - 01:50 PM UTC
2           EMAIL_SENT # 04/19/2024 - 09:31 PM IST
3           EMAIL_SENT # 04/26/2024 - 01:48 PM EDT
4           EMAIL_SENT # 12/31/2024 - 11:07 AM EST
...                                            ...
157164               ERROR # Invalid email address
157165                       ERROR # Invalid email
157166               ERROR # Invalid email address
157167  EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC
157168                       ERROR # Invalid email

[157169 rows x 2 columns]

In [353]:
df = df.merge(last_status_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST
...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email

In [ ]:
from datetime import datetime
import pytz



# Filter for 'OPENED' emails
opened_emails = eng[eng['raw_status'].str.contains('OPENED', na=False)]

# Get most recent open time per email
last_opened = opened_emails.groupby('Email')['status_time'].max().reset_index(name='last_open_time')

# Current time in UTC to match status_time
now_utc = datetime.now(pytz.UTC)

# Calculate days since last email was opened
last_opened['days_since_last_email_opened'] = (now_utc - last_opened['last_open_time']).dt.days

# Final output
last_opened[['Email', 'days_since_last_email_opened']]

In [360]:
df = df.merge(last_opened, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,last_open_time_x,days_since_last_email_opened_x,last_open_time_y,days_since_last_email_opened_y
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,NaT,NaN,NaT,NaN
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,NaT,NaN,NaT,NaN
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,NaT,NaN,NaT,NaN
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,NaT,NaN,NaT,NaN
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,NaT,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,NaT,NaN,NaT,NaN
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,NaT,NaN,NaT,NaN
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,NaT,NaN,NaT,NaN
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,2024-07-23 09:45:00+00:00,316.0,2024-07-23 09:45:00+00:00,316.0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,NaT,NaN,NaT,NaN

In [363]:
from datetime import datetime
import pytz

# Convert status_time to datetime with US/Eastern timezone
eastern = pytz.timezone('US/Eastern')
eng['status_time'] = pd.to_datetime(eng['status_time'], errors='coerce').dt.tz_convert('US/Eastern')

# Filter rows where raw_status indicates the email was sent
sent_emails = eng[eng['raw_status'].str.contains('SENT', na=False)]

# Get the most recent sent time per email
last_sent = sent_emails.groupby('Email')['status_time'].max().reset_index(name='last_sent_time')

# Current time in US/Eastern
now_et = datetime.now(eastern)

# Calculate days since last email was sent
last_sent['days_since_last_email_sent'] = (now_et - last_sent['last_sent_time']).dt.days

# Final output
last_sent[['Email', 'days_since_last_email_sent']]

                                          Email  days_since_last_email_sent
0                       9fake@thomasfellows.com                       347.0
1                           Adaku.Ude@sfdph.org                       214.0
2                               Ahess@amgen.com                       411.0
3                 Carlos.Perez@thermofisher.com                       404.0
4       CarlosOliverMontejano.Ramirez@magna.com                       148.0
...                                         ...                         ...
156533               å©§å¼ @ashleyfurniture.com                         NaN
156534                       å¸†æ¨@its.jnj.com                         NaN
156535                       æ´å¼ @its.jnj.com                         NaN
156536                        è”šæ±ÿ.æ–‡@gm.com                       309.0
156537                     é˜³é˜³.é­@aecom.com                         NaN

[156538 rows x 2 columns]

In [365]:
df = df.merge(last_sent, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,last_open_time_x,days_since_last_email_opened_x,last_open_time_y,days_since_last_email_opened_y,last_sent_time,days_since_last_email_sent
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,NaT,NaN,NaT,NaN,2024-06-22 11:26:00-04:00,347.0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,NaT,NaN,NaT,NaN,2024-11-02 09:50:00-04:00,214.0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,NaT,NaN,NaT,NaN,2024-04-19 12:01:00-04:00,411.0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,NaT,NaN,NaT,NaN,2024-04-26 09:48:00-04:00,404.0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,NaT,NaN,NaT,NaN,2025-01-07 07:57:00-05:00,148.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,NaT,NaN,NaT,NaN,NaT,NaN
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,NaT,NaN,NaT,NaN,NaT,NaN
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,NaT,NaN,NaT,NaN,NaT,NaN
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,2024-07-23 09:45:00+00:00,316.0,2024-07-23 09:45:00+00:00,316.0,2024-07-30 12:58:00-04:00,309.0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,NaT,NaN,NaT,NaN,NaT,NaN

In [367]:
from datetime import datetime
import pytz

# Define Eastern Timezone
eastern = pytz.timezone('US/Eastern')

# Convert status_time to datetime with US/Eastern timezone
eng['status_time'] = pd.to_datetime(eng['status_time'], errors='coerce')

# If timestamps are naive, localize; if UTC-aware, convert to Eastern
if eng['status_time'].dt.tz is None:
    eng['status_time'] = eng['status_time'].dt.tz_localize('US/Eastern')
else:
    eng['status_time'] = eng['status_time'].dt.tz_convert('US/Eastern')

# Get first sent time per Email
first_sent = eng[eng['raw_status'].str.contains('SENT', na=False)] \
    .groupby('Email')['status_time'].min().reset_index(name='first_sent_time')

# Get first opened time per Email
first_open = eng[eng['raw_status'].str.contains('OPENED', na=False)] \
    .groupby('Email')['status_time'].min().reset_index(name='first_open_time')

# Merge and calculate days taken to open first email
merged = pd.merge(first_sent, first_open, on='Email')
merged['days_to_open_first_email'] = (merged['first_open_time'] - merged['first_sent_time']).dt.days

# Final output
merged[['Email', 'days_to_open_first_email']]

                         Email  days_to_open_first_email
0        a.akingboju@apple.com                      -4.0
1      a.alexander@samsung.com                       6.0
2        a.calzola@samsung.com                       6.0
3        a.freitas@samsung.com                      69.0
4     a.harrington@samsung.com                       7.0
...                        ...                       ...
9231     zrogers@coca-cola.com                      -2.0
9232        zsiddiq@rivian.com                       2.0
9233    zstoller@coca-cola.com                      22.0
9234   zurielsuarez@dswinc.com                       7.0
9235         è”šæ±ÿ.æ–‡@gm.com                      67.0

[9236 rows x 2 columns]

In [369]:
df = df.merge(first_open, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,last_open_time_x,days_since_last_email_opened_x,last_open_time_y,days_since_last_email_opened_y,last_sent_time,days_since_last_email_sent,first_open_time
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,NaT,NaN,NaT,NaN,2024-06-22 11:26:00-04:00,347.0,NaT
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,NaT,NaN,NaT,NaN,2024-11-02 09:50:00-04:00,214.0,NaT
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,NaT,NaN,NaT,NaN,2024-04-19 12:01:00-04:00,411.0,NaT
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,NaT,NaN,NaT,NaN,2024-04-26 09:48:00-04:00,404.0,NaT
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,NaT,NaN,NaT,NaN,2025-01-07 07:57:00-05:00,148.0,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,NaT,NaN,NaT,NaN,NaT,NaN,NaT
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,NaT,NaN,NaT,NaN,NaT,NaN,NaT
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,NaT,NaN,NaT,NaN,NaT,NaN,NaT
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,2024-07-23 09:45:00+00:00,316.0,2024-07-23 09:45:00+00:00,316.0,2024-07-30 12:58:00-04:00,309.0,2024-07-23 05:45:00-04:00
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,NaT,NaN,NaT,NaN,NaT,NaN,NaT

In [375]:
from datetime import datetime
import pytz

# Define Eastern Timezone
eastern = pytz.timezone('US/Eastern')

# Convert status_time to datetime with US/Eastern timezone
eng['status_time'] = pd.to_datetime(eng['status_time'], errors='coerce')

# Handle timezone: localize if naive, else convert to US/Eastern
if eng['status_time'].dt.tz is None:
    eng['status_time'] = eng['status_time'].dt.tz_localize('US/Eastern')
else:
    eng['status_time'] = eng['status_time'].dt.tz_convert('US/Eastern')

# Filter rows with 'OPENED' in raw_status
opened = eng[eng['raw_status'].str.contains('OPENED', na=False)]

# Get first open time per email
first_open_mail = opened.groupby('Email')['status_time'].min().reset_index(name='first_open_time')

# Current time in Eastern
now_et = datetime.now(eastern)

# Calculate days since first email open
first_open_mail['days_since_first_email_open'] = (now_et - first_open_mail['first_open_time']).dt.days

# Final output
first_open_mail[['Email', 'days_since_first_email_open']]

                         Email  days_since_first_email_open
0        a.akingboju@apple.com                          127
1      a.alexander@samsung.com                          349
2        a.calzola@samsung.com                          350
3        a.freitas@samsung.com                          301
4     a.harrington@samsung.com                          349
...                        ...                          ...
9231     zrogers@coca-cola.com                          455
9232        zsiddiq@rivian.com                          314
9233    zstoller@coca-cola.com                          434
9234   zurielsuarez@dswinc.com                          278
9235         è”šæ±ÿ.æ–‡@gm.com                          316

[9236 rows x 2 columns]

In [376]:
df = df.merge(first_open_mail, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,last_open_time_x,days_since_last_email_opened_x,last_open_time_y,days_since_last_email_opened_y,last_sent_time,days_since_last_email_sent,first_open_time_x,first_open_time_y,days_since_first_email_open
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,NaT,NaN,NaT,NaN,2024-06-22 11:26:00-04:00,347.0,NaT,NaT,NaN
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,NaT,NaN,NaT,NaN,2024-11-02 09:50:00-04:00,214.0,NaT,NaT,NaN
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,NaT,NaN,NaT,NaN,2024-04-19 12:01:00-04:00,411.0,NaT,NaT,NaN
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,NaT,NaN,NaT,NaN,2024-04-26 09:48:00-04:00,404.0,NaT,NaT,NaN
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,NaT,NaN,NaT,NaN,2025-01-07 07:57:00-05:00,148.0,NaT,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,2024-07-23 09:45:00+00:00,316.0,2024-07-23 09:45:00+00:00,316.0,2024-07-30 12:58:00-04:00,309.0,2024-07-23 05:45:00-04:00,2024-07-23 05:45:00-04:00,316.0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN

In [380]:
import pandas as pd

# Convert to datetime in main DataFrame
eng['first_email_sent_date'] = pd.to_datetime(eng['first_email_sent_date'], errors='coerce')
eng['final_status_time'] = pd.to_datetime(eng['final_status_time'], errors='coerce')

# Total emails sent per Email
total_sent = eng.groupby('Email').size().reset_index(name='total_sent')

# Aggregate first and last dates per Email
date_range = eng.groupby('Email').agg(
    first_date=('first_email_sent_date', 'min'),
    last_date=('final_status_time', 'max')
).reset_index()

# Convert to datetime
date_range['first_date'] = pd.to_datetime(date_range['first_date'], errors='coerce')
date_range['last_date'] = pd.to_datetime(date_range['last_date'], errors='coerce')

# Remove timezones if present
date_range['first_date'] = date_range['first_date'].dt.tz_localize(None)
date_range['last_date'] = date_range['last_date'].dt.tz_localize(None)

# Calculate total days targeted (inclusive)
date_range['total_days_targeted'] = (date_range['last_date'] - date_range['first_date']).dt.days + 1
date_range['total_days_targeted'] = date_range['total_days_targeted'].replace(0, 1)

# Merge with total emails sent
engagement_df = total_sent.merge(date_range, on='Email', how='left')

# Compute engagement density
engagement_df['engagement_density'] = engagement_df['total_sent'] / engagement_df['total_days_targeted']

# Final output
engagement_df = engagement_df[['Email', 'engagement_density']]
print(engagement_df)

/var/folders/mk/bw48nl8s6sx_zsk7rhlf53vr0000gn/T/ipykernel_70501/2860413596.py:4: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  eng['first_email_sent_date'] = pd.to_datetime(eng['first_email_sent_date'], errors='coerce')

                                          Email  engagement_density
0                       9fake@thomasfellows.com            0.583333
1                           Adaku.Ude@sfdph.org            0.722222
2                               Ahess@amgen.com            0.375000
3                 Carlos.Perez@thermofisher.com            1.000000
4       CarlosOliverMontejano.Ramirez@magna.com                 NaN
...                                         ...                 ...
157164               å©§å¼ @ashleyfurniture.com            0.666667
157165                       å¸†æ¨@its.jnj.com            1.000000
157166                       æ´å¼ @its.jnj.com            1.000000
157167                        è”šæ±ÿ.æ–‡@gm.com            0.526316
157168                     é˜³é˜³.é­@aecom.com            0.097561

[157169 rows x 2 columns]

In [382]:
df = df.merge(engagement_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,last_open_time_x,days_since_last_email_opened_x,last_open_time_y,days_since_last_email_opened_y,last_sent_time,days_since_last_email_sent,first_open_time_x,first_open_time_y,days_since_first_email_open,engagement_density
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,NaT,NaN,NaT,NaN,2024-06-22 11:26:00-04:00,347.0,NaT,NaT,NaN,0.583333
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,NaT,NaN,NaT,NaN,2024-11-02 09:50:00-04:00,214.0,NaT,NaT,NaN,0.722222
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,NaT,NaN,NaT,NaN,2024-04-19 12:01:00-04:00,411.0,NaT,NaT,NaN,0.375000
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,NaT,NaN,NaT,NaN,2024-04-26 09:48:00-04:00,404.0,NaT,NaT,NaN,1.000000
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,NaT,NaN,NaT,NaN,2025-01-07 07:57:00-05:00,148.0,NaT,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN,0.666667
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN,1.000000
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN,1.000000
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,2024-07-23 09:45:00+00:00,316.0,2024-07-23 09:45:00+00:00,316.0,2024-07-30 12:58:00-04:00,309.0,2024-07-23 05:45:00-04:00,2024-07-23 05:45:00-04:00,316.0,0.526316
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN,0.097561

In [385]:
import pandas as pd

# Step 1: Convert email_sent_et to datetime
eng['email_sent_et'] = pd.to_datetime(eng['email_sent_et'], errors='coerce')

# Step 2: Drop rows where conversion failed (optional but helps debugging)
# You can uncomment this if needed
# eng = eng[eng['email_sent_et'].notnull()]

# Step 3: Check if conversion worked
if not pd.api.types.is_datetime64_any_dtype(eng['email_sent_et']):
    print("email_sent_et is not datetime — check input format")
else:
    # Step 4: Extract hour and mark morning emails
    eng['sent_hour'] = eng['email_sent_et'].dt.hour
    eng['is_morning'] = eng['sent_hour'].between(6, 11)

    # Step 5: Count morning emails per prospect
    morning_email_df = eng[eng['is_morning']].groupby('Email').size().reset_index(name='total_morning_emails')

    # Step 6: Ensure all emails are represented (including those with 0 morning emails)
    all_emails = eng[['Email']].drop_duplicates()
    morning_email_df = all_emails.merge(morning_email_df, on='Email', how='left')
    morning_email_df['total_morning_emails'] = morning_email_df['total_morning_emails'].fillna(0).astype(int)

    # Step 7: Output result
    print(morning_email_df)

email_sent_et is not datetime — check input format

/var/folders/mk/bw48nl8s6sx_zsk7rhlf53vr0000gn/T/ipykernel_70501/2747820442.py:4: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  eng['email_sent_et'] = pd.to_datetime(eng['email_sent_et'], errors='coerce')

In [386]:
df = df.merge(morning_email_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,days_since_last_email_opened_x,last_open_time_y,days_since_last_email_opened_y,last_sent_time,days_since_last_email_sent,first_open_time_x,first_open_time_y,days_since_first_email_open,engagement_density,total_morning_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,NaN,NaT,NaN,2024-06-22 11:26:00-04:00,347.0,NaT,NaT,NaN,0.583333,3
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,NaN,NaT,NaN,2024-11-02 09:50:00-04:00,214.0,NaT,NaT,NaN,0.722222,8
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,NaN,NaT,NaN,2024-04-19 12:01:00-04:00,411.0,NaT,NaT,NaN,0.375000,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,NaN,NaT,NaN,2024-04-26 09:48:00-04:00,404.0,NaT,NaT,NaN,1.000000,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,NaN,NaT,NaN,2025-01-07 07:57:00-05:00,148.0,NaT,NaT,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN,0.666667,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN,1.000000,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN,1.000000,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,316.0,2024-07-23 09:45:00+00:00,316.0,2024-07-30 12:58:00-04:00,309.0,2024-07-23 05:45:00-04:00,2024-07-23 05:45:00-04:00,316.0,0.526316,20
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN,0.097561,0

In [388]:
# Mark afternoon emails (12 PM to 4:59 PM)
eng['is_afternoon'] = eng['sent_hour'].between(12, 16)

# Count per email
afternoon_email_df = eng[eng['is_afternoon']].groupby('Email').size().reset_index(name='total_afternoon_emails')

# Ensure all emails included
all_emails = eng[['Email']].drop_duplicates()
afternoon_email_df = all_emails.merge(afternoon_email_df, on='Email', how='left')
afternoon_email_df['total_afternoon_emails'] = afternoon_email_df['total_afternoon_emails'].fillna(0).astype(int)

print(afternoon_email_df)

KeyError: 'sent_hour'

In [ ]:
df = df.merge(afternoon_email_df, on='Email', how='left')
df

In [ ]:
# Mark evening emails (5 PM to 8:59 PM)
eng['is_evening'] = eng['sent_hour'].between(17, 20)

# Count per email
evening_email_df = eng[eng['is_evening']].groupby('Email').size().reset_index(name='total_evening_emails')

# Merge with all emails
evening_email_df = all_emails.merge(evening_email_df, on='Email', how='left')
evening_email_df['total_evening_emails'] = evening_email_df['total_evening_emails'].fillna(0).astype(int)

print(evening_email_df)

In [ ]:
df = df.merge(evening_email_df, on='Email', how='left')
df

In [394]:
# Mark night emails (9 PM to 11:59 PM OR 12 AM to 5:59 AM)
eng['is_night'] = eng['sent_hour'].between(21, 23) | eng['sent_hour'].between(0, 5)

# Count per email
night_email_df = eng[eng['is_night']].groupby('Email').size().reset_index(name='total_night_emails')

# Merge with all emails
night_email_df = all_emails.merge(night_email_df, on='Email', how='left')
night_email_df['total_night_emails'] = night_email_df['total_night_emails'].fillna(0).astype(int)

print(night_email_df)

KeyError: 'sent_hour'

In [396]:
df = df.merge(night_email_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,last_open_time_y,days_since_last_email_opened_y,last_sent_time,days_since_last_email_sent,first_open_time_x,first_open_time_y,days_since_first_email_open,engagement_density,total_morning_emails,total_night_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,NaT,NaN,2024-06-22 11:26:00-04:00,347.0,NaT,NaT,NaN,0.583333,3,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,NaT,NaN,2024-11-02 09:50:00-04:00,214.0,NaT,NaT,NaN,0.722222,8,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,NaT,NaN,2024-04-19 12:01:00-04:00,411.0,NaT,NaT,NaN,0.375000,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,NaT,NaN,2024-04-26 09:48:00-04:00,404.0,NaT,NaT,NaN,1.000000,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,NaT,NaN,2025-01-07 07:57:00-05:00,148.0,NaT,NaT,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaT,NaN,NaT,NaN,NaT,NaT,NaN,0.666667,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaT,NaN,NaT,NaN,NaT,NaT,NaN,1.000000,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaT,NaN,NaT,NaN,NaT,NaT,NaN,1.000000,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,2024-07-23 09:45:00+00:00,316.0,2024-07-30 12:58:00-04:00,309.0,2024-07-23 05:45:00-04:00,2024-07-23 05:45:00-04:00,316.0,0.526316,20,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaT,NaN,NaT,NaN,NaT,NaT,NaN,0.097561,0,0

In [399]:
# Ensure datetime
eng['email_sent_et'] = pd.to_datetime(eng['email_sent_et'], errors='coerce')

# Extract day of week (0 = Monday, ..., 6 = Sunday)
eng['sent_day'] = eng['email_sent_et'].dt.dayofweek

# Get all unique emails
all_emails = eng[['Email']].drop_duplicates()

In [400]:
eng['is_monday'] = eng['sent_day'] == 0
monday_df = eng[eng['is_monday']].groupby('Email').size().reset_index(name='total_monday_emails')
monday_df = all_emails.merge(monday_df, on='Email', how='left')
monday_df['total_monday_emails'] = monday_df['total_monday_emails'].fillna(0).astype(int)

print(monday_df)

                                          Email  total_monday_emails
0                       9fake@thomasfellows.com                    0
1                           Adaku.Ude@sfdph.org                    2
2                               Ahess@amgen.com                    0
3                 Carlos.Perez@thermofisher.com                    0
4       CarlosOliverMontejano.Ramirez@magna.com                    0
...                                         ...                  ...
157164               å©§å¼ @ashleyfurniture.com                    0
157165                       å¸†æ¨@its.jnj.com                    0
157166                       æ´å¼ @its.jnj.com                    0
157167                        è”šæ±ÿ.æ–‡@gm.com                    4
157168                     é˜³é˜³.é­@aecom.com                    0

[157169 rows x 2 columns]

In [402]:
df = df.merge(monday_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,days_since_last_email_opened_y,last_sent_time,days_since_last_email_sent,first_open_time_x,first_open_time_y,days_since_first_email_open,engagement_density,total_morning_emails,total_night_emails,total_monday_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,NaN,2024-06-22 11:26:00-04:00,347.0,NaT,NaT,NaN,0.583333,3,0,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,NaN,2024-11-02 09:50:00-04:00,214.0,NaT,NaT,NaN,0.722222,8,0,2
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,NaN,2024-04-19 12:01:00-04:00,411.0,NaT,NaT,NaN,0.375000,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,NaN,2024-04-26 09:48:00-04:00,404.0,NaT,NaT,NaN,1.000000,0,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,NaN,2025-01-07 07:57:00-05:00,148.0,NaT,NaT,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaN,NaT,NaN,NaT,NaT,NaN,0.666667,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaN,NaT,NaN,NaT,NaT,NaN,1.000000,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaN,NaT,NaN,NaT,NaT,NaN,1.000000,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,316.0,2024-07-30 12:58:00-04:00,309.0,2024-07-23 05:45:00-04:00,2024-07-23 05:45:00-04:00,316.0,0.526316,20,0,4
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaN,NaT,NaN,NaT,NaT,NaN,0.097561,0,0,0

In [403]:
eng['is_tuesday'] = eng['sent_day'] == 1
tuesday_df = eng[eng['is_tuesday']].groupby('Email').size().reset_index(name='total_tuesday_emails')
tuesday_df = all_emails.merge(tuesday_df, on='Email', how='left')
tuesday_df['total_tuesday_emails'] = tuesday_df['total_tuesday_emails'].fillna(0).astype(int)

print(tuesday_df)

                                          Email  total_tuesday_emails
0                       9fake@thomasfellows.com                     1
1                           Adaku.Ude@sfdph.org                     2
2                               Ahess@amgen.com                     0
3                 Carlos.Perez@thermofisher.com                     1
4       CarlosOliverMontejano.Ramirez@magna.com                     0
...                                         ...                   ...
157164               å©§å¼ @ashleyfurniture.com                     0
157165                       å¸†æ¨@its.jnj.com                     0
157166                       æ´å¼ @its.jnj.com                     0
157167                        è”šæ±ÿ.æ–‡@gm.com                     8
157168                     é˜³é˜³.é­@aecom.com                     0

[157169 rows x 2 columns]

In [404]:
df = df.merge(tuesday_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,last_sent_time,days_since_last_email_sent,first_open_time_x,first_open_time_y,days_since_first_email_open,engagement_density,total_morning_emails,total_night_emails,total_monday_emails,total_tuesday_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,2024-06-22 11:26:00-04:00,347.0,NaT,NaT,NaN,0.583333,3,0,0,1
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,2024-11-02 09:50:00-04:00,214.0,NaT,NaT,NaN,0.722222,8,0,2,2
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,2024-04-19 12:01:00-04:00,411.0,NaT,NaT,NaN,0.375000,0,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,2024-04-26 09:48:00-04:00,404.0,NaT,NaT,NaN,1.000000,0,0,0,1
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,2025-01-07 07:57:00-05:00,148.0,NaT,NaT,NaN,NaN,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaT,NaN,NaT,NaT,NaN,0.666667,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaT,NaN,NaT,NaT,NaN,1.000000,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaT,NaN,NaT,NaT,NaN,1.000000,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,2024-07-30 12:58:00-04:00,309.0,2024-07-23 05:45:00-04:00,2024-07-23 05:45:00-04:00,316.0,0.526316,20,0,4,8
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaT,NaN,NaT,NaT,NaN,0.097561,0,0,0,0

In [405]:
eng['is_wednesday'] = eng['sent_day'] == 2
wednesday_df = eng[eng['is_wednesday']].groupby('Email').size().reset_index(name='total_wednesday_emails')
wednesday_df = all_emails.merge(wednesday_df, on='Email', how='left')
wednesday_df['total_wednesday_emails'] = wednesday_df['total_wednesday_emails'].fillna(0).astype(int)

print(wednesday_df)

                                          Email  total_wednesday_emails
0                       9fake@thomasfellows.com                       1
1                           Adaku.Ude@sfdph.org                       2
2                               Ahess@amgen.com                       0
3                 Carlos.Perez@thermofisher.com                       1
4       CarlosOliverMontejano.Ramirez@magna.com                       0
...                                         ...                     ...
157164               å©§å¼ @ashleyfurniture.com                       0
157165                       å¸†æ¨@its.jnj.com                       0
157166                       æ´å¼ @its.jnj.com                       0
157167                        è”šæ±ÿ.æ–‡@gm.com                       8
157168                     é˜³é˜³.é­@aecom.com                       0

[157169 rows x 2 columns]

In [406]:
df = df.merge(wednesday_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,days_since_last_email_sent,first_open_time_x,first_open_time_y,days_since_first_email_open,engagement_density,total_morning_emails,total_night_emails,total_monday_emails,total_tuesday_emails,total_wednesday_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,347.0,NaT,NaT,NaN,0.583333,3,0,0,1,1
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,214.0,NaT,NaT,NaN,0.722222,8,0,2,2,2
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,411.0,NaT,NaT,NaN,0.375000,0,0,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,404.0,NaT,NaT,NaN,1.000000,0,0,0,1,1
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,148.0,NaT,NaT,NaN,NaN,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaN,NaT,NaT,NaN,0.666667,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaN,NaT,NaT,NaN,1.000000,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaN,NaT,NaT,NaN,1.000000,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,309.0,2024-07-23 05:45:00-04:00,2024-07-23 05:45:00-04:00,316.0,0.526316,20,0,4,8,8
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaN,NaT,NaT,NaN,0.097561,0,0,0,0,0

In [407]:
eng['is_thursday'] = eng['sent_day'] == 3
thursday_df = eng[eng['is_thursday']].groupby('Email').size().reset_index(name='total_thursday_emails')
thursday_df = all_emails.merge(thursday_df, on='Email', how='left')
thursday_df['total_thursday_emails'] = thursday_df['total_thursday_emails'].fillna(0).astype(int)

print(thursday_df)

                                          Email  total_thursday_emails
0                       9fake@thomasfellows.com                      1
1                           Adaku.Ude@sfdph.org                      3
2                               Ahess@amgen.com                      0
3                 Carlos.Perez@thermofisher.com                      1
4       CarlosOliverMontejano.Ramirez@magna.com                      0
...                                         ...                    ...
157164               å©§å¼ @ashleyfurniture.com                      0
157165                       å¸†æ¨@its.jnj.com                      0
157166                       æ´å¼ @its.jnj.com                      0
157167                        è”šæ±ÿ.æ–‡@gm.com                      8
157168                     é˜³é˜³.é­@aecom.com                      0

[157169 rows x 2 columns]

In [408]:
df = df.merge(thursday_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,first_open_time_x,first_open_time_y,days_since_first_email_open,engagement_density,total_morning_emails,total_night_emails,total_monday_emails,total_tuesday_emails,total_wednesday_emails,total_thursday_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,NaT,NaT,NaN,0.583333,3,0,0,1,1,1
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,NaT,NaT,NaN,0.722222,8,0,2,2,2,3
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,NaT,NaT,NaN,0.375000,0,0,0,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,NaT,NaT,NaN,1.000000,0,0,0,1,1,1
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,NaT,NaT,NaN,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaT,NaT,NaN,0.666667,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaT,NaT,NaN,1.000000,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaT,NaT,NaN,1.000000,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,2024-07-23 05:45:00-04:00,2024-07-23 05:45:00-04:00,316.0,0.526316,20,0,4,8,8,8
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaT,NaT,NaN,0.097561,0,0,0,0,0,0

In [409]:
eng['is_friday'] = eng['sent_day'] == 4
friday_df = eng[eng['is_friday']].groupby('Email').size().reset_index(name='total_friday_emails')
friday_df = all_emails.merge(friday_df, on='Email', how='left')
friday_df['total_friday_emails'] = friday_df['total_friday_emails'].fillna(0).astype(int)

print(friday_df)

                                          Email  total_friday_emails
0                       9fake@thomasfellows.com                    1
1                           Adaku.Ude@sfdph.org                    2
2                               Ahess@amgen.com                    1
3                 Carlos.Perez@thermofisher.com                    1
4       CarlosOliverMontejano.Ramirez@magna.com                    0
...                                         ...                  ...
157164               å©§å¼ @ashleyfurniture.com                    0
157165                       å¸†æ¨@its.jnj.com                    0
157166                       æ´å¼ @its.jnj.com                    0
157167                        è”šæ±ÿ.æ–‡@gm.com                    7
157168                     é˜³é˜³.é­@aecom.com                    0

[157169 rows x 2 columns]

In [410]:
df = df.merge(friday_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,first_open_time_y,days_since_first_email_open,engagement_density,total_morning_emails,total_night_emails,total_monday_emails,total_tuesday_emails,total_wednesday_emails,total_thursday_emails,total_friday_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,NaT,NaN,0.583333,3,0,0,1,1,1,1
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,NaT,NaN,0.722222,8,0,2,2,2,3,2
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,NaT,NaN,0.375000,0,0,0,0,0,0,1
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,NaT,NaN,1.000000,0,0,0,1,1,1,1
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,NaT,NaN,NaN,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaT,NaN,0.666667,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaT,NaN,1.000000,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaT,NaN,1.000000,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,2024-07-23 05:45:00-04:00,316.0,0.526316,20,0,4,8,8,8,7
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaT,NaN,0.097561,0,0,0,0,0,0,0

In [411]:
eng['is_saturday'] = eng['sent_day'] == 5
saturday_df = eng[eng['is_saturday']].groupby('Email').size().reset_index(name='total_saturday_emails')
saturday_df = all_emails.merge(saturday_df, on='Email', how='left')
saturday_df['total_saturday_emails'] = saturday_df['total_saturday_emails'].fillna(0).astype(int)

print(saturday_df)

                                          Email  total_saturday_emails
0                       9fake@thomasfellows.com                      1
1                           Adaku.Ude@sfdph.org                      2
2                               Ahess@amgen.com                      0
3                 Carlos.Perez@thermofisher.com                      0
4       CarlosOliverMontejano.Ramirez@magna.com                      0
...                                         ...                    ...
157164               å©§å¼ @ashleyfurniture.com                      0
157165                       å¸†æ¨@its.jnj.com                      0
157166                       æ´å¼ @its.jnj.com                      0
157167                        è”šæ±ÿ.æ–‡@gm.com                      4
157168                     é˜³é˜³.é­@aecom.com                      0

[157169 rows x 2 columns]

In [412]:
df = df.merge(saturday_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,days_since_first_email_open,engagement_density,total_morning_emails,total_night_emails,total_monday_emails,total_tuesday_emails,total_wednesday_emails,total_thursday_emails,total_friday_emails,total_saturday_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,NaN,0.583333,3,0,0,1,1,1,1,1
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,NaN,0.722222,8,0,2,2,2,3,2,2
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,NaN,0.375000,0,0,0,0,0,0,1,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,NaN,1.000000,0,0,0,1,1,1,1,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,NaN,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaN,0.666667,0,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaN,1.000000,0,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,NaN,1.000000,0,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,316.0,0.526316,20,0,4,8,8,8,7,4
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,NaN,0.097561,0,0,0,0,0,0,0,0

In [413]:
eng['is_sunday'] = eng['sent_day'] == 6
sunday_df = eng[eng['is_sunday']].groupby('Email').size().reset_index(name='total_sunday_emails')
sunday_df = all_emails.merge(sunday_df, on='Email', how='left')
sunday_df['total_sunday_emails'] = sunday_df['total_sunday_emails'].fillna(0).astype(int)

print(sunday_df)

                                          Email  total_sunday_emails
0                       9fake@thomasfellows.com                    0
1                           Adaku.Ude@sfdph.org                    0
2                               Ahess@amgen.com                    0
3                 Carlos.Perez@thermofisher.com                    0
4       CarlosOliverMontejano.Ramirez@magna.com                    0
...                                         ...                  ...
157164               å©§å¼ @ashleyfurniture.com                    0
157165                       å¸†æ¨@its.jnj.com                    0
157166                       æ´å¼ @its.jnj.com                    0
157167                        è”šæ±ÿ.æ–‡@gm.com                    0
157168                     é˜³é˜³.é­@aecom.com                    0

[157169 rows x 2 columns]

In [414]:
df = df.merge(sunday_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,engagement_density,total_morning_emails,total_night_emails,total_monday_emails,total_tuesday_emails,total_wednesday_emails,total_thursday_emails,total_friday_emails,total_saturday_emails,total_sunday_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,0.583333,3,0,0,1,1,1,1,1,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,0.722222,8,0,2,2,2,3,2,2,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,0.375000,0,0,0,0,0,0,1,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,1.000000,0,0,0,1,1,1,1,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,NaN,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0.666667,0,0,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,1.000000,0,0,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,1.000000,0,0,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,0.526316,20,0,4,8,8,8,7,4,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0.097561,0,0,0,0,0,0,0,0,0

In [416]:
import pandas as pd
from datetime import datetime, timedelta

# Step 1: Convert to datetime (if not done already)
eng['email_sent_et'] = pd.to_datetime(eng['email_sent_et'], errors='coerce')

# Step 2: Calculate the 4-week-ago timestamp from "now"
now = pd.Timestamp.now(tz='US/Eastern')  # Assuming ET timezone awareness
four_weeks_ago = now - timedelta(weeks=4)

# Step 3: Filter emails sent in the last 4 weeks
eng['is_last_4_weeks'] = eng['email_sent_et'] >= four_weeks_ago

# Step 4: Group by Email
last_4_weeks_df = eng[eng['is_last_4_weeks']].groupby('Email').size().reset_index(name='total_last_4_weeks_emails')

# Step 5: Ensure all emails are present (even if 0 sent in last 4 weeks)
all_emails = eng[['Email']].drop_duplicates()
last_4_weeks_df = all_emails.merge(last_4_weeks_df, on='Email', how='left')
last_4_weeks_df['total_last_4_weeks_emails'] = last_4_weeks_df['total_last_4_weeks_emails'].fillna(0).astype(int)

# Step 6: Output result
print(last_4_weeks_df)

                                          Email  total_last_4_weeks_emails
0                       9fake@thomasfellows.com                          0
1                           Adaku.Ude@sfdph.org                          0
2                               Ahess@amgen.com                          0
3                 Carlos.Perez@thermofisher.com                          0
4       CarlosOliverMontejano.Ramirez@magna.com                          0
...                                         ...                        ...
157164               å©§å¼ @ashleyfurniture.com                          0
157165                       å¸†æ¨@its.jnj.com                          0
157166                       æ´å¼ @its.jnj.com                          0
157167                        è”šæ±ÿ.æ–‡@gm.com                          0
157168                     é˜³é˜³.é­@aecom.com                          0

[157169 rows x 2 columns]

In [417]:
df = df.merge(last_4_weeks_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,total_morning_emails,total_night_emails,total_monday_emails,total_tuesday_emails,total_wednesday_emails,total_thursday_emails,total_friday_emails,total_saturday_emails,total_sunday_emails,total_last_4_weeks_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,3,0,0,1,1,1,1,1,0,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,8,0,2,2,2,3,2,2,0,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,0,0,0,0,0,0,1,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,0,0,0,1,1,1,1,0,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,20,0,4,8,8,8,7,4,0,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0

In [418]:
# 8 weeks ago
eight_weeks_ago = now - timedelta(weeks=8)

# Filter emails
eng['is_last_8_weeks'] = eng['email_sent_et'] >= eight_weeks_ago

# Group and count
last_8_weeks_df = eng[eng['is_last_8_weeks']].groupby('Email').size().reset_index(name='total_last_8_weeks_emails')

# Merge with all emails
last_8_weeks_df = all_emails.merge(last_8_weeks_df, on='Email', how='left')
last_8_weeks_df['total_last_8_weeks_emails'] = last_8_weeks_df['total_last_8_weeks_emails'].fillna(0).astype(int)

print(last_8_weeks_df)

                                          Email  total_last_8_weeks_emails
0                       9fake@thomasfellows.com                          0
1                           Adaku.Ude@sfdph.org                          0
2                               Ahess@amgen.com                          0
3                 Carlos.Perez@thermofisher.com                          0
4       CarlosOliverMontejano.Ramirez@magna.com                          0
...                                         ...                        ...
157164               å©§å¼ @ashleyfurniture.com                          0
157165                       å¸†æ¨@its.jnj.com                          0
157166                       æ´å¼ @its.jnj.com                          0
157167                        è”šæ±ÿ.æ–‡@gm.com                          0
157168                     é˜³é˜³.é­@aecom.com                          0

[157169 rows x 2 columns]

In [419]:
df = df.merge(last_8_weeks_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,total_night_emails,total_monday_emails,total_tuesday_emails,total_wednesday_emails,total_thursday_emails,total_friday_emails,total_saturday_emails,total_sunday_emails,total_last_4_weeks_emails,total_last_8_weeks_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,0,0,1,1,1,1,1,0,0,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,0,2,2,2,3,2,2,0,0,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,0,0,0,0,0,1,0,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,0,0,1,1,1,1,0,0,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,0,4,8,8,8,7,4,0,0,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0

In [420]:
# 12 weeks ago
twelve_weeks_ago = now - timedelta(weeks=12)

# Filter emails
eng['is_last_12_weeks'] = eng['email_sent_et'] >= twelve_weeks_ago

# Group and count
last_12_weeks_df = eng[eng['is_last_12_weeks']].groupby('Email').size().reset_index(name='total_last_12_weeks_emails')

# Merge with all emails
last_12_weeks_df = all_emails.merge(last_12_weeks_df, on='Email', how='left')
last_12_weeks_df['total_last_12_weeks_emails'] = last_12_weeks_df['total_last_12_weeks_emails'].fillna(0).astype(int)

print(last_12_weeks_df)

                                          Email  total_last_12_weeks_emails
0                       9fake@thomasfellows.com                           0
1                           Adaku.Ude@sfdph.org                           0
2                               Ahess@amgen.com                           0
3                 Carlos.Perez@thermofisher.com                           0
4       CarlosOliverMontejano.Ramirez@magna.com                           0
...                                         ...                         ...
157164               å©§å¼ @ashleyfurniture.com                           0
157165                       å¸†æ¨@its.jnj.com                           0
157166                       æ´å¼ @its.jnj.com                           0
157167                        è”šæ±ÿ.æ–‡@gm.com                           0
157168                     é˜³é˜³.é­@aecom.com                           0

[157169 rows x 2 columns]

In [421]:
df = df.merge(last_12_weeks_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,total_monday_emails,total_tuesday_emails,total_wednesday_emails,total_thursday_emails,total_friday_emails,total_saturday_emails,total_sunday_emails,total_last_4_weeks_emails,total_last_8_weeks_emails,total_last_12_weeks_emails
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,0,1,1,1,1,1,0,0,0,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,2,2,2,3,2,2,0,0,0,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,0,0,0,0,1,0,0,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,0,1,1,1,1,0,0,0,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,4,8,8,8,7,4,0,0,0,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0

In [423]:
import pandas as pd
from datetime import timedelta

# Convert and localize the datetime
eng['status_time_clean'] = pd.to_datetime(eng['status_time_clean'], errors='coerce')
eng['status_time_clean'] = eng['status_time_clean'].dt.tz_localize('US/Eastern', ambiguous='NaT', nonexistent='NaT')

# Get current ET time
now = pd.Timestamp.now(tz='US/Eastern')
four_weeks_ago = now - timedelta(weeks=4)

# Filter: Opened in last 4 weeks
opened_last_4_weeks = eng[
    (eng['status'].str.lower() == 'open') &
    (eng['status_time_clean'] >= four_weeks_ago)
]

# Group and count
opened_4w_df = opened_last_4_weeks.groupby('Email').size().reset_index(name='total_opened_last_4_weeks')

# Include all emails
all_emails = eng[['Email']].drop_duplicates()
opened_4w_df = all_emails.merge(opened_4w_df, on='Email', how='left')
opened_4w_df['total_opened_last_4_weeks'] = opened_4w_df['total_opened_last_4_weeks'].fillna(0).astype(int)

# Final output
print(opened_4w_df)

/var/folders/mk/bw48nl8s6sx_zsk7rhlf53vr0000gn/T/ipykernel_70501/478118261.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  eng['status_time_clean'] = pd.to_datetime(eng['status_time_clean'], errors='coerce')

                                          Email  total_opened_last_4_weeks
0                       9fake@thomasfellows.com                          0
1                           Adaku.Ude@sfdph.org                          0
2                               Ahess@amgen.com                          0
3                 Carlos.Perez@thermofisher.com                          0
4       CarlosOliverMontejano.Ramirez@magna.com                          0
...                                         ...                        ...
157164               å©§å¼ @ashleyfurniture.com                          0
157165                       å¸†æ¨@its.jnj.com                          0
157166                       æ´å¼ @its.jnj.com                          0
157167                        è”šæ±ÿ.æ–‡@gm.com                          0
157168                     é˜³é˜³.é­@aecom.com                          0

[157169 rows x 2 columns]

In [424]:
df = df.merge(opened_4w_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,total_tuesday_emails,total_wednesday_emails,total_thursday_emails,total_friday_emails,total_saturday_emails,total_sunday_emails,total_last_4_weeks_emails,total_last_8_weeks_emails,total_last_12_weeks_emails,total_opened_last_4_weeks
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,1,1,1,1,1,0,0,0,0,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,2,2,3,2,2,0,0,0,0,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,0,0,0,1,0,0,0,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,1,1,1,1,0,0,0,0,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,8,8,8,7,4,0,0,0,0,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0

In [425]:
# Calculate 8 weeks ago from now
eight_weeks_ago = now - timedelta(weeks=8)

# Filter opened emails in last 8 weeks
opened_last_8_weeks = eng[
    (eng['status'].str.lower() == 'open') &
    (eng['status_time_clean'] >= eight_weeks_ago)
]

# Group by Email and count
opened_8w_df = opened_last_8_weeks.groupby('Email').size().reset_index(name='total_opened_last_8_weeks')

# Merge with all emails to include zeros
opened_8w_df = all_emails.merge(opened_8w_df, on='Email', how='left')
opened_8w_df['total_opened_last_8_weeks'] = opened_8w_df['total_opened_last_8_weeks'].fillna(0).astype(int)

print(opened_8w_df)

                                          Email  total_opened_last_8_weeks
0                       9fake@thomasfellows.com                          0
1                           Adaku.Ude@sfdph.org                          0
2                               Ahess@amgen.com                          0
3                 Carlos.Perez@thermofisher.com                          0
4       CarlosOliverMontejano.Ramirez@magna.com                          0
...                                         ...                        ...
157164               å©§å¼ @ashleyfurniture.com                          0
157165                       å¸†æ¨@its.jnj.com                          0
157166                       æ´å¼ @its.jnj.com                          0
157167                        è”šæ±ÿ.æ–‡@gm.com                          0
157168                     é˜³é˜³.é­@aecom.com                          0

[157169 rows x 2 columns]

In [426]:
df = df.merge(opened_8w_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,total_wednesday_emails,total_thursday_emails,total_friday_emails,total_saturday_emails,total_sunday_emails,total_last_4_weeks_emails,total_last_8_weeks_emails,total_last_12_weeks_emails,total_opened_last_4_weeks,total_opened_last_8_weeks
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,1,1,1,1,0,0,0,0,0,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,2,3,2,2,0,0,0,0,0,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,0,0,1,0,0,0,0,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,1,1,1,0,0,0,0,0,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,8,8,7,4,0,0,0,0,0,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0

In [427]:
# Calculate 12 weeks ago from now
twelve_weeks_ago = now - timedelta(weeks=12)

# Filter opened emails in last 12 weeks
opened_last_12_weeks = eng[
    (eng['status'].str.lower() == 'open') &
    (eng['status_time_clean'] >= twelve_weeks_ago)
]

# Group by Email and count
opened_12w_df = opened_last_12_weeks.groupby('Email').size().reset_index(name='total_opened_last_12_weeks')

# Merge with all emails to include zeros
opened_12w_df = all_emails.merge(opened_12w_df, on='Email', how='left')
opened_12w_df['total_opened_last_12_weeks'] = opened_12w_df['total_opened_last_12_weeks'].fillna(0).astype(int)

print(opened_12w_df)

                                          Email  total_opened_last_12_weeks
0                       9fake@thomasfellows.com                           0
1                           Adaku.Ude@sfdph.org                           0
2                               Ahess@amgen.com                           0
3                 Carlos.Perez@thermofisher.com                           0
4       CarlosOliverMontejano.Ramirez@magna.com                           0
...                                         ...                         ...
157164               å©§å¼ @ashleyfurniture.com                           0
157165                       å¸†æ¨@its.jnj.com                           0
157166                       æ´å¼ @its.jnj.com                           0
157167                        è”šæ±ÿ.æ–‡@gm.com                           0
157168                     é˜³é˜³.é­@aecom.com                           0

[157169 rows x 2 columns]

In [428]:
df = df.merge(opened_12w_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,total_thursday_emails,total_friday_emails,total_saturday_emails,total_sunday_emails,total_last_4_weeks_emails,total_last_8_weeks_emails,total_last_12_weeks_emails,total_opened_last_4_weeks,total_opened_last_8_weeks,total_opened_last_12_weeks
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,1,1,1,0,0,0,0,0,0,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,3,2,2,0,0,0,0,0,0,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,0,1,0,0,0,0,0,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,1,1,0,0,0,0,0,0,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,8,7,4,0,0,0,0,0,0,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0

In [429]:
import pandas as pd

# Convert email_sent_et and status_time_clean to datetime
eng['email_sent_et'] = pd.to_datetime(eng['email_sent_et'], errors='coerce')
eng['status_time_clean'] = pd.to_datetime(eng['status_time_clean'], errors='coerce')

# Handle timezone for email_sent_et
if eng['email_sent_et'].dt.tz is None:
    eng['email_sent_et'] = eng['email_sent_et'].dt.tz_localize('US/Eastern', ambiguous='NaT', nonexistent='NaT')
else:
    eng['email_sent_et'] = eng['email_sent_et'].dt.tz_convert('US/Eastern')

# Handle timezone for status_time_clean (date when email was opened)
if eng['status_time_clean'].dt.tz is None:
    eng['status_time_clean'] = eng['status_time_clean'].dt.tz_localize('US/Eastern', ambiguous='NaT', nonexistent='NaT')
else:
    eng['status_time_clean'] = eng['status_time_clean'].dt.tz_convert('US/Eastern')

# Extract day of week from status_time_clean (when email was opened)
eng['opened_day_of_week'] = eng['status_time_clean'].dt.dayofweek

# Filter for opened emails on weekends (Saturday=5, Sunday=6)
opened_weekends = eng[
    (eng['status'].str.lower() == 'open') &
    (eng['opened_day_of_week'].isin([5, 6]))
]

# Group by Email and count total opened emails on weekends
opened_weekends_df = opened_weekends.groupby('Email').size().reset_index(name='total_opened_weekends')

# Get all unique emails to ensure everyone is included in output
all_emails = eng[['Email']].drop_duplicates()

# Merge with all emails, fill missing counts with 0
opened_weekends_df = all_emails.merge(opened_weekends_df, on='Email', how='left')
opened_weekends_df['total_opened_weekends'] = opened_weekends_df['total_opened_weekends'].fillna(0).astype(int)

print(opened_weekends_df)

                                          Email  total_opened_weekends
0                       9fake@thomasfellows.com                      0
1                           Adaku.Ude@sfdph.org                      0
2                               Ahess@amgen.com                      0
3                 Carlos.Perez@thermofisher.com                      0
4       CarlosOliverMontejano.Ramirez@magna.com                      0
...                                         ...                    ...
157164               å©§å¼ @ashleyfurniture.com                      0
157165                       å¸†æ¨@its.jnj.com                      0
157166                       æ´å¼ @its.jnj.com                      0
157167                        è”šæ±ÿ.æ–‡@gm.com                      0
157168                     é˜³é˜³.é­@aecom.com                      0

[157169 rows x 2 columns]

In [430]:
df = df.merge(opened_weekends_df, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,total_friday_emails,total_saturday_emails,total_sunday_emails,total_last_4_weeks_emails,total_last_8_weeks_emails,total_last_12_weeks_emails,total_opened_last_4_weeks,total_opened_last_8_weeks,total_opened_last_12_weeks,total_opened_weekends
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,1,1,0,0,0,0,0,0,0,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,2,2,0,0,0,0,0,0,0,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,1,0,0,0,0,0,0,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,1,0,0,0,0,0,0,0,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,7,4,0,0,0,0,0,0,0,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0

In [431]:
import pandas as pd

# Ensure status column is lowercase for comparison
eng['status_lower'] = eng['status'].str.lower()

# Find unique emails who have ever opened an email
opened_emails = eng[eng['status_lower'] == 'open']['Email'].unique()

# Create a DataFrame of all unique emails
all_emails = pd.DataFrame(eng['Email'].unique(), columns=['Email'])

# Add binary column 'has_ever_opened': 1 if in opened_emails, else 0
all_emails['has_ever_opened'] = all_emails['Email'].isin(opened_emails).astype(int)

print(all_emails)

                                          Email  has_ever_opened
0                       9fake@thomasfellows.com                0
1                           Adaku.Ude@sfdph.org                0
2                               Ahess@amgen.com                0
3                 Carlos.Perez@thermofisher.com                0
4       CarlosOliverMontejano.Ramirez@magna.com                0
...                                         ...              ...
157164               å©§å¼ @ashleyfurniture.com                0
157165                       å¸†æ¨@its.jnj.com                0
157166                       æ´å¼ @its.jnj.com                0
157167                        è”šæ±ÿ.æ–‡@gm.com                0
157168                     é˜³é˜³.é­@aecom.com                0

[157169 rows x 2 columns]

In [432]:
df = df.merge(all_emails, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,total_saturday_emails,total_sunday_emails,total_last_4_weeks_emails,total_last_8_weeks_emails,total_last_12_weeks_emails,total_opened_last_4_weeks,total_opened_last_8_weeks,total_opened_last_12_weeks,total_opened_weekends,has_ever_opened
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,1,0,0,0,0,0,0,0,0,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,2,0,0,0,0,0,0,0,0,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,0,0,0,0,0,0,0,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,0,0,0,0,0,0,0,0,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,4,0,0,0,0,0,0,0,0,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0

In [433]:
import pandas as pd

# Ensure 'status' column is lowercase for consistent comparison
eng['status_lower'] = eng['status'].str.lower()

# Find unique emails who have ever unsubscribed
unsubscribed_emails = eng[eng['status_lower'] == 'unsubscribe']['Email'].unique()

# Create a DataFrame of all unique emails
all_emails = pd.DataFrame(eng['Email'].unique(), columns=['Email'])

# Add binary column 'has_ever_unsubscribed': 1 if unsubscribed, else 0
all_emails['has_ever_unsubscribed'] = all_emails['Email'].isin(unsubscribed_emails).astype(int)

print(all_emails)

                                          Email  has_ever_unsubscribed
0                       9fake@thomasfellows.com                      0
1                           Adaku.Ude@sfdph.org                      0
2                               Ahess@amgen.com                      0
3                 Carlos.Perez@thermofisher.com                      0
4       CarlosOliverMontejano.Ramirez@magna.com                      0
...                                         ...                    ...
157164               å©§å¼ @ashleyfurniture.com                      0
157165                       å¸†æ¨@its.jnj.com                      0
157166                       æ´å¼ @its.jnj.com                      0
157167                        è”šæ±ÿ.æ–‡@gm.com                      0
157168                     é˜³é˜³.é­@aecom.com                      0

[157169 rows x 2 columns]

In [434]:
df = df.merge(all_emails, on='Email', how='left')
df

,Email,total_emails,total_emails_clicked,total_emails_unsubscribed,total_emails_bounced,total_emails_responded,has_unsubscribed_first_email,email_bounce_rate,email_open_rate,last_email_status,...,total_sunday_emails,total_last_4_weeks_emails,total_last_8_weeks_emails,total_last_12_weeks_emails,total_opened_last_4_weeks,total_opened_last_8_weeks,total_opened_last_12_weeks,total_opened_weekends,has_ever_opened,has_ever_unsubscribed
0,9fake@thomasfellows.com,7,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 06/22/2024 - 03:26 PM UTC,...,0,0,0,0,0,0,0,0,0,0
1,Adaku.Ude@sfdph.org,13,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 11/02/2024 - 01:50 PM UTC,...,0,0,0,0,0,0,0,0,0,0
2,Ahess@amgen.com,3,NaN,NaN,1.0,NaN,0,0.000000,0.000,EMAIL_SENT # 04/19/2024 - 09:31 PM IST,...,0,0,0,0,0,0,0,0,0,0
3,Carlos.Perez@thermofisher.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,EMAIL_SENT # 04/26/2024 - 01:48 PM EDT,...,0,0,0,0,0,0,0,0,0,0
4,CarlosOliverMontejano.Ramirez@magna.com,22,NaN,NaN,2.0,NaN,0,0.045455,0.000,EMAIL_SENT # 12/31/2024 - 11:07 AM EST,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157164,å©§å¼ @ashleyfurniture.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157165,å¸†æ¨@its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0
157166,æ´å¼ @its.jnj.com,2,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email address,...,0,0,0,0,0,0,0,0,0,0
157167,è”šæ±ÿ.æ–‡@gm.com,40,1.0,NaN,NaN,NaN,0,0.000000,0.025,EMAIL_NOT_SENT # 07/30/2024 - 04:58 PM UTC,...,0,0,0,0,0,0,0,0,0,0
157168,é˜³é˜³.é­@aecom.com,4,NaN,NaN,NaN,NaN,0,0.000000,0.000,ERROR # Invalid email,...,0,0,0,0,0,0,0,0,0,0

In [461]:
df.to_csv('final1.csv',index=False)